version: '3'

services:
  portainer-ce:
    image: 'portainer/portainer-ce:latest'
    restart: always
    ports:
      - '9000:9000'
      - '8000:8000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/home/docker/portainer:/data'
    container_name: portainer
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true
